# Generated by Django 4.2.dev20220902080224 on 2022-10-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fullname',
            field=models.CharField(default=1232, max_length=50, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='pnumber',
            field=models.PositiveBigIntegerField(default=3454, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
