# Generated by Django 4.2.dev20220902080224 on 2022-10-07 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0003_remove_booking_sum_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.PositiveIntegerField(verbose_name='Sum')),
                ('fullname', models.CharField(max_length=50, verbose_name='Full name')),
                ('pnumber', models.PositiveBigIntegerField(verbose_name='Phone number')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pnumber',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.AddField(
            model_name='bookinginformation',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookinginformation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
