# Generated by Django 4.2.dev20220902080224 on 2022-10-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookinginformation_remove_booking_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='fullname',
            field=models.CharField(default=1, max_length=50, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='pnumber',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='sum',
            field=models.PositiveIntegerField(default=1, verbose_name='Sum'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookingInformation',
        ),
    ]
