# Generated by Django 4.2.dev20220902080224 on 2022-10-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_fullname_booking_pnumber_booking_sum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='sum',
        ),
    ]
